version: '3'
services:
  backstage:
    build: 
      dockerfile: ./packages/backend/Dockerfile
      context: .
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DATABASE: "backstage"
    ports:
      - "3000:3000" #frontend
      - "7007:7007" #backend

  postgres:
    image: postgres
    container_name: pg-backstage
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "backstage"
    volumes:
      - /tmp/backstage-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
